#!/usr/bin/env python3
"""
Test karaoke subtitle rendering with FFmpeg.
"""

import sys
import subprocess

def parse_word_timing(filename):
    """Parse section-X-words.txt into list of (start, end, text) tuples."""
    words = []
    with open(filename, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            parts = line.split(':', 2)
            if len(parts) < 3:
                continue
            start = float(parts[0])
            end = float(parts[1])
            text = parts[2]
            words.append((start, end, text))
    return words

def format_ass_time(seconds):
    """Format seconds to ASS time format HH:MM:SS.cc"""
    hours = int(seconds // 3600)
    minutes = int((seconds % 3600) // 60)
    secs = int(seconds % 60)
    centis = int((seconds % 1) * 100)
    return f"{hours:02d}:{minutes:02d}:{secs:02d}.{centis:02d}"

def generate_karaoke_ass(words, output_path):
    """Generate ASS file with karaoke highlighting from word timing."""

    if not words:
        print("No words to process!")
        return

    # Group words into subtitle segments
    segments = []
    current_segment_words = []
    current_start = None

    for i, (start, end, text) in enumerate(words):
        if current_start is None:
            current_start = start

        current_segment_words.append((start, end, text))

        # End segment if we've accumulated enough content or it's the last word
        if len(current_segment_words) >= 6 or i == len(words) - 1:
            segment_end = current_segment_words[-1][1]
            segments.append((current_start, segment_end, current_segment_words))
            current_segment_words = []
            current_start = None

    # Generate ASS content
    ass_lines = []
    ass_lines.append('[Script Info]')
    ass_lines.append('; Generated by test-karaoke.py')
    ass_lines.append('ScriptType: v4.00+')
    ass_lines.append('PlayResX: 640')
    ass_lines.append('PlayResY: 480')
    ass_lines.append('ScaledBorderAndShadow: yes')
    ass_lines.append('')
    ass_lines.append('[V4+ Styles]')
    ass_lines.append('Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding')
    # Alignment 8 = top center, MarginV 10 = 10px from top
    ass_lines.append('Style: Default,Heiti SC,35,&HFFFFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,0,100,100,0,0,1,2,0,2,10,10,150,1')
    ass_lines.append('')
    ass_lines.append('[Events]')
    ass_lines.append('Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text')
    ass_lines.append('')

    for seg_start, seg_end, seg_words in segments:
        # Format text WITHOUT karaoke tags (just plain text)
        plain_text = ''.join(w[2] for w in seg_words)

        start_time = format_ass_time(seg_start + 0.1)
        end_time = format_ass_time(seg_end + 0.3)

        ass_lines.append(f'Dialogue: 0,{start_time},{end_time},Default,,0,0,0,,{plain_text}')

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(ass_lines))

    print(f"Generated ASS: {output_path}")
    print(f"Total words: {len(words)}")
    print(f"Total segments: {len(segments)}")

def main():
    words_file = 'output/segments/intro/section-0-words.txt'
    ass_output = 'output/segments/intro/test-karaoke.ass'
    mp3_input = 'output/segments/intro/section-0.mp3'
    mp4_output = 'output/segments/intro/test-karaoke.mp4'

    print("Parsing word timing...")
    words = parse_word_timing(words_file)
    print(f"Loaded {len(words)} words")

    print("\nGenerating ASS with karaoke...")
    generate_karaoke_ass(words, ass_output)

    print("\nGenerating MP4 with FFmpeg...")
    # Small resolution for subtitles only, white background
    ffmpeg_cmd = [
        'ffmpeg', '-y',
        '-f', 'lavfi', '-i', 'color=c=white:s=640x480:d=60',
        '-i', mp3_input,
        '-vf', f"ass='{ass_output}'",
        '-c:v', 'libx264', '-pix_fmt', 'yuv420p',
        '-c:a', 'aac', '-b:a', '192k',
        '-shortest',
        '-map', '0:v', '-map', '1:a',
        '-t', '60',
        mp4_output
    ]

    print(f"Running: {' '.join(ffmpeg_cmd)}")
    result = subprocess.run(ffmpeg_cmd, capture_output=True, text=True)

    if result.returncode == 0:
        print(f"\nGenerated MP4: {mp4_output}")
    else:
        print(f"\nFFmpeg error:\n{result.stderr}")

if __name__ == '__main__':
    main()
