// Mock phonetics API
// Returns phonetic transcriptions for each word in a text
// This can be replaced with a real TTS or dictionary API

const mockPhonetics: Record<string, string> = {
  'sleep': '/sliːp/',
  'is': '/ɪz/',
  'essential': '/ɪˈsenʃəl/',
  'for': '/fɔːr/',
  'good': '/ɡʊd/',
  'health': '/helθ/',
  'the': '/ðə/',
  'brain': '/breɪn/',
  'and': '/ænd/',
  'memory': '/ˈmeməri/',
  'learning': '/ˈlɜːrnɪŋ/',
  'a': '/ə/',
  'helps': '/helps/',
  'us': '/ʌs/',
  'concentrate': '/ˈkɒnsəntreɪt/',
  'better': '/ˈbetər/',
  'during': '/ˈdjʊərɪŋ/',
  'day': '/deɪ/',
  'practice': '/ˈpræktɪs/',
  'reading': '/ˈriːdɪŋ/',
  'every': '/ˈevri/',
  'can': '/kæn/',
  'improve': '/ɪmˈpruːv/',
  'your': '/jɔːr/',
  'vocabulary': '/vəˈkæbjʊləri/',
  'quickly': '/ˈkwɪkli/',
  'english': '/ˈɪŋɡlɪʃ/',
  'language': '/ˈlæŋɡwɪdʒ/',
  'skills': '/skɪlz/',
  'important': '/ɪmˈpɔːrtənt/',
  'understand': '/ˌʌndərˈstænd/',
  'words': '/wɜːrdz/',
  'sentences': '/ˈsentənsɪz/',
  'study': '/ˈstʌdi/',
  'knowledge': '/ˈnɒlɪdʒ/',
  'article': '/ˈɑːrtɪkl/',
  'this': '/ðɪs/',
  'that': '/ðæt/',
  'with': '/wɪð/',
  'you': '/juː/',
  'to': '/tuː/',
  'of': '/əv/',
  'in': '/ɪn/',
  'it': '/ɪt/',
  'on': '/ɒn/',
  'as': '/æz/',
  'at': '/æt/',
  'be': '/biː/',
  'by': '/baɪ/',
  'from': '/frɒm/',
  'or': '/ɔːr/',
  'an': '/æn/',
  'are': '/ɑːr/',
  'was': '/wɒz/',
  'were': '/wɜːr/',
  'have': '/hæv/',
  'has': '/hæz/',
  'will': '/wɪl/',
  'would': '/wʊd/',
  'could': '/kʊd/',
  'should': '/ʃʊd/',
  'there': '/ðeər/',
  'their': '/ðeər/',
  'what': '/wɒt/',
  'which': '/wɪtʃ/',
  'who': '/huː/',
  'when': '/wen/',
  'where': '/weər/',
  'why': '/waɪ/',
  'how': '/haʊ/',
  'all': '/ɔːl/',
  'each': '/iːtʃ/',
  'make': '/meɪk/',
  'like': '/laɪk/',
  'time': '/taɪm/',
  'just': '/dʒʌst/',
  'know': '/nəʊ/',
  'take': '/teɪk/',
  'people': '/ˈpiːpl/',
  'into': '/ˈɪntuː/',
  'year': '/jɪər/',
  'my': '/maɪ/',
  'also': '/ˈɔːlsəʊ/',
  'think': '/θɪŋk/',
  'work': '/wɜːrk/',
  'first': '/fɜːrst/',
  'even': '/ˈiːvn/',
  'new': '/njuː/',
  'want': '/wɒnt/',
  'because': '/bɪˈkɒz/',
  'any': '/ˈeni/',
  'these': '/ðiːz/',
  'give': '/ɡɪv/',
  'most': '/məʊst/',
  'great': '/ɡreɪt/',
  'same': '/seɪm/',
  'another': '/əˈnʌðər/',
  'come': '/kʌm/',
  'find': '/faɪnd/',
  'long': '/lɒŋ/',
  'much': '/mʌtʃ/',
  'need': '/niːd/',
  'over': '/ˈəʊvər/',
  'such': '/sʌtʃ/',
  'thing': '/θɪŋ/',
  'through': '/θruː/',
  'very': '/ˈveri/',
  'well': '/wel/',
  'while': '/waɪl/',
  'world': '/wɜːrld/',
  'about': '/əˈbaʊt/',
  'after': '/ˈɑːftər/',
  'again': '/əˈɡen/',
  'being': '/ˈbiːɪŋ/',
  'between': '/bɪˈtwiːn/',
  'both': '/bəʊθ/',
  'down': '/daʊn/',
  'example': '/ɪɡˈzɑːmpl/',
  'few': '/fjuː/',
  'get': '/ɡet/',
  'here': '/hɪər/',
  'house': '/haʊs/',
  'keep': '/kiːp/',
  'last': '/lɑːst/',
  'life': '/laɪf/',
  'look': '/lʊk/',
  'more': '/mɔːr/',
  'other': '/ˈʌðər/',
  'part': '/pɑːrt/',
  'place': '/pleɪs/',
  'point': '/pɔɪnt/',
  'right': '/raɪt/',
  'school': '/skuːl/',
  'small': '/smɔːl/',
  'some': '/sʌm/',
  'sound': '/saʊnd/',
  'still': '/stɪl/',
  'story': '/ˈstɔːri/',
  'student': '/ˈstjuːdənt/',
  'system': '/ˈsɪstəm/',
  'those': '/ðəʊz/',
  'three': '/θriː/',
  'too': '/tuː/',
  'try': '/traɪ/',
  'up': '/ʌp/',
  'use': '/juːz/',
  'water': '/ˈwɔːtər/',
  'way': '/weɪ/',
  'week': '/wiːk/',
  'without': '/wɪðˈaʊt/',
  'write': '/raɪt/',
  'young': '/jʌŋ/',
}

export default defineEventHandler(async (event) => {
  const query = getQuery(event)
  const text = (query.text as string || '').trim()

  if (!text) {
    throw createError({
      statusCode: 400,
      message: 'Text parameter is required'
    })
  }

  // Split text into words and find phonetics for each
  const words = text.split(/\s+/).map(word => {
    // Remove punctuation for lookup
    const cleanWord = word.toLowerCase().replace(/[^\w]/g, '')
    const phonetic = mockPhonetics[cleanWord] || `/${cleanWord}/`

    return {
      word: cleanWord,
      original: word,
      phonetic
    }
  })

  return { words }
})