
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMMA IDENTIFIER LPAREN NUMBER RPARENexpr : LPAREN callee args RPARENcallee : IDENTIFIERargs : empty \n            | expr COMMA argsempty : '
    
_lr_action_items = {'LPAREN':([0,3,4,9,],[2,2,-2,2,]),'$end':([1,8,],[0,-1,]),'IDENTIFIER':([2,],[4,]),'RPAREN':([3,4,5,6,9,10,],[-5,-2,8,-3,-5,-4,]),'COMMA':([7,8,],[9,-1,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([0,3,9,],[1,7,7,]),'callee':([2,],[3,]),'args':([3,9,],[5,10,]),'empty':([3,9,],[6,6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expr","S'",1,None,None,None),
  ('expr -> LPAREN callee args RPAREN','expr',4,'p_expr','parse_call_expr.py',29),
  ('callee -> IDENTIFIER','callee',1,'p_callee','parse_call_expr.py',33),
  ('args -> empty','args',1,'p_args','parse_call_expr.py',37),
  ('args -> expr COMMA args','args',3,'p_args','parse_call_expr.py',38),
  ('empty -> <empty>','empty',0,'p_empty','parse_call_expr.py',45),
]
