
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = "'\x12\xeb>8\xd9g\xd5\x16\xa7R\x8b.G\x90\xb8"
    
_lr_action_items = {'$end':([2,3,5,13,14,15,16,17,18,19,],[-9,0,-2,-7,-1,-8,-3,-6,-4,-5,]),'RPAREN':([2,8,13,15,16,17,18,19,],[-9,15,-7,-8,-3,-6,-4,-5,]),'NAME':([0,],[1,]),'EQUALS':([1,],[7,]),'NUMBER':([0,4,6,7,9,10,11,12,],[2,2,2,2,2,2,2,2,]),'PLUS':([2,5,8,13,14,15,16,17,18,19,],[-9,9,9,-7,9,-8,-3,-6,-4,-5,]),'LPAREN':([0,4,6,7,9,10,11,12,],[4,4,4,4,4,4,4,4,]),'TIMES':([2,5,8,13,14,15,16,17,18,19,],[-9,12,12,-7,12,-8,12,-6,12,-5,]),'MINUS':([0,2,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,],[6,-9,6,11,6,6,11,6,6,6,6,-7,11,-8,-3,-6,-4,-5,]),'DIVIDE':([2,5,8,13,14,15,16,17,18,19,],[-9,10,10,-7,10,-8,10,-6,10,-5,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,4,6,7,9,10,11,12,],[5,8,13,14,16,17,18,19,]),'statement':([0,],[3,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> NAME EQUALS expression','statement',3,'p_statement_assign','calc.py',60),
  ('statement -> expression','statement',1,'p_statement_expr','calc.py',64),
  ('expression -> expression PLUS expression','expression',3,'p_expression_binop','calc.py',68),
  ('expression -> expression MINUS expression','expression',3,'p_expression_binop','calc.py',69),
  ('expression -> expression TIMES expression','expression',3,'p_expression_binop','calc.py',70),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression_binop','calc.py',71),
  ('expression -> MINUS expression','expression',2,'p_expression_uminus','calc.py',78),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','calc.py',82),
  ('expression -> NUMBER','expression',1,'p_expression_number','calc.py',86),
]
