struct ngx_http_request_s {
uint32_t signature;
ngx_connection_t *connection;
void *ctx;
void *main_conf;
void *srv_conf;
void *loc_conf;
ngx_http_event_handler_pt read_event_handler;
ngx_http_event_handler_pt write_event_handler;
ngx_http_cache_t *cache;
ngx_http_upstream_t *upstream;
ngx_array_t *upstream_states;
ngx_pool_t *pool;
ngx_buf_t *header_in;
ngx_http_headers_in_t headers_in;
ngx_http_headers_out_t headers_out;
ngx_http_request_body_t *request_body;
time_t lingering_time;
time_t start_sec;
ngx_msec_t start_msec;
ngx_uint_t method;
ngx_uint_t http_version;
ngx_str_t request_line;
ngx_str_t uri;
ngx_str_t args;
ngx_str_t exten;
ngx_str_t unparsed_uri;
ngx_str_t method_name;
ngx_str_t http_protocol;
ngx_str_t schema;
ngx_chain_t *out;
ngx_http_request_t *main;
ngx_http_request_t *parent;
ngx_http_postponed_request_t *postponed;
ngx_http_post_subrequest_t *post_subrequest;
ngx_http_posted_request_t *posted_requests;
ngx_int_t phase_handler;
ngx_http_handler_pt content_handler;
ngx_uint_t access_code;
ngx_http_variable_value_t *variables;
ngx_uint_t ncaptures;
int *captures;
u_char *captures_data;
size_t limit_rate;
size_t limit_rate_after;
size_t header_size;
off_t request_length;
ngx_uint_t err_status;
ngx_http_connection_t *http_connection;
ngx_http_v2_stream_t *stream;
ngx_http_log_handler_pt log_handler;
ngx_http_cleanup_t *cleanup;
unsigned int count;
unsigned int subrequests;
unsigned int blocked;
unsigned int aio;
unsigned int http_state;
unsigned int complex_uri;
unsigned int quoted_uri;
unsigned int plus_in_uri;
unsigned int space_in_uri;
unsigned int empty_path_in_uri;
unsigned int invalid_header;
unsigned int add_uri_to_alias;
unsigned int valid_location;
unsigned int valid_unparsed_uri;
unsigned int uri_changed;
unsigned int uri_changes;
unsigned int request_body_in_single_buf;
unsigned int request_body_in_file_only;
unsigned int request_body_in_persistent_file;
unsigned int request_body_in_clean_file;
unsigned int request_body_file_group_access;
unsigned int request_body_file_log_level;
unsigned int request_body_no_buffering;
unsigned int subrequest_in_memory;
unsigned int waited;
unsigned int cached;
unsigned int gzip_tested;
unsigned int gzip_ok;
unsigned int gzip_vary;
unsigned int realloc_captures;
unsigned int proxy;
unsigned int bypass_cache;
unsigned int no_cache;
unsigned int limit_conn_status;
unsigned int limit_req_status;
unsigned int limit_rate_set;
unsigned int limit_rate_after_set;
unsigned int pipeline;
unsigned int chunked;
unsigned int header_only;
unsigned int expect_trailers;
unsigned int keepalive;
unsigned int lingering_close;
unsigned int discard_body;
unsigned int reading_body;
unsigned int internal;
unsigned int error_page;
unsigned int filter_finalize;
unsigned int post_action;
unsigned int request_complete;
unsigned int request_output;
unsigned int header_sent;
unsigned int expect_tested;
unsigned int root_tested;
unsigned int done;
unsigned int logged;
unsigned int buffered;
unsigned int main_filter_need_in_memory;
unsigned int filter_need_in_memory;
unsigned int filter_need_temporary;
unsigned int preserve_body;
unsigned int allow_ranges;
unsigned int subrequest_ranges;
unsigned int single_range;
unsigned int disable_not_modified;
unsigned int stat_reading;
unsigned int stat_writing;
unsigned int stat_processing;
unsigned int background;
unsigned int health_check;
ngx_uint_t state;
ngx_uint_t header_hash;
ngx_uint_t lowcase_index;
u_char lowcase_header[31];
u_char *header_name_start;
u_char *header_name_end;
u_char *header_start;
u_char *header_end;
u_char *uri_start;
u_char *uri_end;
u_char *uri_ext;
u_char *args_start;
u_char *request_start;
u_char *request_end;
u_char *method_end;
u_char *schema_start;
u_char *schema_end;
u_char *host_start;
u_char *host_end;
u_char *port_start;
u_char *port_end;
unsigned int http_minor;
unsigned int http_major;
};
